# Generated by Django 4.1 on 2022-10-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL("ALTER TABLE smart_device_readings ADD id serial;")
    ]