# Generated by Django 4.1 on 2022-10-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SmartDeviceReadings",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("date", models.TextField(blank=True, null=True)),
                ("timestamp", models.TextField(blank=True, null=True)),
                ("gateway_name", models.TextField(blank=True, null=True)),
                ("gateway_model", models.TextField(blank=True, null=True)),
                ("gateway_serial", models.TextField(blank=True, null=True)),
                ("device_name", models.TextField(blank=True, null=True)),
                ("device_serial", models.TextField(blank=True, null=True)),
                (
                    "line_to_neutral_voltage_phase_a",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "line_to_neutral_voltage_phase_b",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "line_to_neutral_voltage_phase_c",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "import_active_energy_overall_total",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "active_power_overall_total",
                    models.FloatField(blank=True, null=True),
                ),
                ("analog_input_channel_1", models.FloatField(blank=True, null=True)),
                ("analog_input_channel_2", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "smart_device_readings",
                "managed": False,
            },
        ),
    ]
