# Generated by Django 4.1 on 2022-10-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartDeviceReadings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "gateway_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gateway_model",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gateway_serial",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "device_serial",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "line_to_neutral_voltage_phase_a",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "line_to_neutral_voltage_phase_b",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "line_to_neutral_voltage_phase_c",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "import_active_energy_overall_total",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "active_power_overall_total",
                    models.FloatField(blank=True, null=True),
                ),
                ("analog_input_channel_1", models.FloatField(blank=True, null=True)),
                ("analog_input_channel_2", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "smart_device_readings",
                "managed": False,
            },
        ),
    ]
