# Generated by Django 4.1 on 2022-10-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_user_employee_id_user_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
