# Generated by Django 4.1 on 2022-10-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
