# Generated by Django 4.1 on 2022-10-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": (("admin", "Admin"), ("operation", "Operation"))},
        ),
        migrations.AlterField(
            model_name="user",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("operation", "Operation"),
                    ("finance", "Finance"),
                ],
                default="operation",
                max_length=40,
            ),
        ),
    ]
