# Generated by Django 4.1 on 2022-09-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_id", models.CharField(max_length=120)),
                ("site", models.CharField(max_length=120)),
                ("zone", models.CharField(max_length=120)),
                ("district", models.CharField(max_length=120)),
                ("activity", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("time", models.DateTimeField()),
            ],
        ),
    ]
