# Generated by Django 4.1 on 2022-10-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_id", models.CharField(max_length=120)),
                ("zone", models.CharField(max_length=120)),
                ("district", models.CharField(max_length=120)),
                ("activity", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("time", models.DateTimeField()),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("asset_name", models.CharField(max_length=240)),
                ("asset_type", models.CharField(max_length=120)),
                ("asset_co_ordinate", models.CharField(max_length=120)),
                ("asset_capacity", models.CharField(max_length=120)),
                ("under_maintenance", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "activitylog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.activitylog",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.activitylog",),
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "activitylog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.activitylog",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.activitylog",),
        ),
        migrations.CreateModel(
            name="UserLog",
            fields=[
                (
                    "activitylog_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.activitylog",
                    ),
                ),
                ("modified_by", models.CharField(max_length=120)),
                ("employee_id", models.CharField(max_length=120)),
                ("email_address", models.CharField(max_length=120)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.activitylog",),
        ),
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription", models.CharField(max_length=120)),
                ("amount_billed", models.FloatField(default=0)),
                ("amount_bought", models.FloatField(default=0)),
                ("duration_days", models.IntegerField()),
                ("time", models.DateTimeField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.site"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=240, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=240)),
                ("co_ordinate", models.CharField(max_length=240)),
                ("company_name", models.CharField(max_length=120)),
                ("company_district", models.CharField(max_length=120)),
                ("company_zone", models.CharField(max_length=120)),
                ("asset_type", models.CharField(max_length=120)),
                ("asset_capacity", models.IntegerField()),
                ("tariff", models.CharField(max_length=120)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="core.site",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activitylog",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="core.site",
            ),
        ),
    ]
