# Generated by Django 4.1 on 2022-10-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Alert",
        ),
    ]
