# Generated by Django 4.1 on 2022-10-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlog",
            name="email_address",
            field=models.EmailField(max_length=254),
        ),
    ]
