# Generated by Django 4.1 on 2022-09-13 12:14

from django.db import migrations
from django.core.management import call_command

def mock_alerts(apps, schema_editor):
    call_command('mockalerts', clear=True, number=100)

def do_nothing(apps, schema_editor):
    call_command('mockalerts', clear=True, number=0)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(mock_alerts, do_nothing)
    ]
