# Generated by Django 4.1 on 2022-09-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20220913_1214"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=120)),
                ("subscription", models.CharField(max_length=120)),
                ("amount_billed", models.FloatField(default=0)),
                ("amount_bought", models.FloatField(default=0)),
                ("duration_days", models.IntegerField()),
                ("time", models.DateTimeField()),
            ],
        ),
    ]
