# Generated by Django 4.1 on 2022-09-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20220913_1434"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("asset_name", models.CharField(max_length=240)),
                ("asset_type", models.CharField(max_length=120)),
                ("asset_co_ordinate", models.CharField(max_length=120)),
                ("asset_capacity", models.CharField(max_length=120)),
                ("time", models.DateTimeField()),
            ],
        ),
    ]
