# Generated by Django 4.1 on 2022-10-11 10:16

from django.db import migrations


def import_device_tariff(apps, schema_editor):
    DeviceTariff = apps.get_model('core', 'devicetariff')

    tariff_data = [
        [54.08, "Band A", "minimum 20hrs"],
        [49.81, "Band B", "16-20 hrs"],
        [43.01, "Band C", "12-16 hrs"],
        [40.82, "Band D", "8-12 hrs"],
        [36.15, "Band E", "less than 8 hrs"]
    ]

    for data in tariff_data:
        DeviceTariff.objects.get_or_create(
            name=data[1],
            price=data[0],
            daily_availability=data[2]
        )
    

def delete_them(apps, schema_editor):
    DeviceTariff = apps.get_model('core', 'devicetariff')
    DeviceTariff.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_devicetariff_remove_device_tariff"),
    ]

    operations = [
        migrations.RunPython(import_device_tariff, delete_them)
    ]
