# Generated by Django 4.1 on 2022-10-11 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20221011_1016"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="tariff",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.devicetariff",
            ),
            preserve_default=False,
        ),
    ]
