# Generated by Django 4.1 on 2022-10-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_device_tariff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "company_type",
                    models.CharField(
                        choices=[("car_energy", "Car Energy")],
                        default="car_energy",
                        max_length=50,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[("energy_monitoring", "Energy monitoring")],
                        default="energy_monitoring",
                        max_length=50,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                ("renewal_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
