# Generated by Django 4.1 on 2022-10-18 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0007_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="users",
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
