# Generated by Django 4.1 on 2022-09-21 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20220921_1538"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.site"
            ),
        ),
    ]
