# Generated by Django 4.1 on 2022-10-18 10:41

from datetime import datetime
from django.db import migrations

default_company = {
    "name": "KBG Russia"
}

def create_company(apps, schema_editor):
    Company = apps.get_model('core', 'company')
    Company.objects.create(
        name=default_company["name"],
        phone_number="1234567890",
        email="email@email.com",
        address="Address",
        renewal_date=datetime.now()
    )

def delete_company(apps, scehma_editor):
    Company = apps.get_model('core', 'company')
    Company.objects.filter(name=default_company["name"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_company_users"),
    ]

    operations = [
        migrations.RunPython(create_company, delete_company)
    ]
