# Generated by Django 4.1 on 2022-09-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_alert_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="under_maintenance",
            field=models.BooleanField(default=False),
        ),
    ]
