# Generated by Django 4.1 on 2022-10-18 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20221018_1041"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.company",
            ),
            preserve_default=False,
        ),
    ]
