# Generated by Django 4.1 on 2022-10-18 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_site_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="company_district",
        ),
        migrations.RemoveField(
            model_name="device",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="device",
            name="company_zone",
        ),
        migrations.AddField(
            model_name="device",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.company",
            ),
            preserve_default=False,
        ),
    ]
