# Generated by Django 4.1 on 2022-09-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_site_under_maintenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
