# Generated by Django 4.1 on 2022-09-28 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_site_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=240, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=240)),
                ("co_ordinate", models.CharField(max_length=240)),
                ("company_name", models.CharField(max_length=120)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.site"
                    ),
                ),
            ],
        ),
    ]
