# Generated by Django 4.1 on 2022-10-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_device_company_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="company_district",
            field=models.CharField(default="District A", max_length=120),
            preserve_default=False,
        ),
    ]
