# Generated by Django 4.1 on 2022-09-28 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="linked_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
