# Generated by Django 4.1 on 2022-09-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_device_linked_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="core.site",
            ),
        ),
    ]
