# Generated by Django 4.1 on 2022-10-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_company_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="core.company",
            ),
        ),
    ]
