# Generated by Django 4.1 on 2022-10-28 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0014_alter_site_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="companies", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
