# Generated by Django 4.1 on 2022-09-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_device_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="asset_capacity",
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="asset_type",
            field=models.CharField(default="Transformer", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="company_district",
            field=models.CharField(default="District A", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="company_zone",
            field=models.CharField(default="oshodi", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="device",
            name="tariff",
            field=models.CharField(default="Band A", max_length=120),
            preserve_default=False,
        ),
    ]
