# Generated by Django 4.1 on 2022-10-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_company_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionhistory",
            old_name="duration_days",
            new_name="days",
        ),
    ]
