# Generated by Django 4.1 on 2022-09-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_device_asset_capacity_device_asset_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="core.site",
            ),
        ),
    ]
