# Generated by Django 4.1 on 2022-11-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_rename_duration_days_transactionhistory_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
