# Generated by Django 4.1 on 2022-09-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_alert_site"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alert",
            old_name="time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="time",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="transactionhistory",
            old_name="time",
            new_name="created_at",
        ),
    ]
