# Generated by Django 4.1 on 2022-09-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_time_alert_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alert",
            old_name="created_at",
            new_name="time",
        ),
        migrations.RenameField(
            model_name="site",
            old_name="created_at",
            new_name="time",
        ),
        migrations.RenameField(
            model_name="transactionhistory",
            old_name="created_at",
            new_name="time",
        ),
    ]
