# Generated by Django 4.1 on 2022-11-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_site_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
