# Generated by Django 4.1 on 2022-11-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_transactionhistory_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=240,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
