# Generated by Django 4.1 on 2022-11-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_device_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="asset_capacity",
        ),
    ]
