# Generated by Django 4.1 on 2022-11-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_site_asset_capacity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="asset_co_ordinate",
        ),
    ]
